const express = require("express");
const app = express();
require("dotenv").config();
app.use(express.json());
let axios = require("axios");
const questions = [
  "Which do you prefer: Book || Movie",
  "Which do you prefer: Phone call || Texting",
  "Which do you prefer: Comedy || Horror",
  "Which are better to watch: Sunsets || Sunrises",
  "Which days do you prefer: Rainy days || Snowy days",
  "You discover a magical object do you: Keep its power a secret || Share it with the world",
  "You're stranded on a desert island do you: Build a shelter first || Search for food immediately",
  "You're in a haunted house do you: Explore it further  || Try to leave as soon as possible",
  "You stumble upon a time machine do you: Travel to the past || Travel to the future",
  "You're in a race do you: Take the shorter, riskier route || Take the longer, safer path",
  "You receive a map with hidden treasure locations do you: Search alone || Make a team",
  "You encounter a time loop do you: Choose to live in it || Try to break free",
  "You're in possession of a truth serum do you: Use it to uncover secrets || Respect others privacy",
  "You're offered a chance to meet your future self would you be: Excited to meet your future self || Afraid to meet your future self",
  "You're granted one wish do you: Use it for personal gain || Use it to change the world",
  "You discover a hidden world within a painting do you: Explore it || Ignore it",
  "You receive a vision of the future: Try to prevent it || Let events occur naturally",
  "Your partner is stressed do you: Plan a relaxing evening together || Give them space to unwind alone",
  "A friend is facing a tough decision do you: Offer your opinion || Help them explore their own options",
  "Someone is dealing with grief do you: Offer words of comfort || Silently show your support through actions",
  "You see a stranger is crying and emotional do you:  Approach them and offer help || Give them privacy to handle their emotions",
  "Your friend is going through a breakup do you: Spend time with them to distract them || Give them space to express their emotions",
  "You've fallen for your best friend do you: Confess your feelings || Keep them hidden to maintain the friendship",
  "Your partner forgets an important anniversary do you: Show your disappointment || Understand it was unintentional",
  "You meet someone from a different culture do you: Try their cultural practices to understand them better || Stick to your own beliefs",
  "Your crush is going through a tough time do you: Offer support immediately || Wait for them to reach out",
  "You discover your partner has a secret past do you: Confront them for honesty || Respect their privacy until they're ready to share",
  "You find out your friend has feelings for you and you don’t feel the same way do you: Talk with them about it || Act as if you don’t know so you don’t risk your friendship",
  "Your partner's career requires relocation do you: Consider moving with them || Prioritise your own career and location",
  "You're interested in someone you've just met do you: Show interest directly || Get to know them better before making a move",
  "Your partner is hesitant about commitment do you: Give them time and space || Initiate a conversation about the future",
  "You and your partner have differing life goals do you: Give your relationship a chance || Consider parting ways",
  "You meet someone who shares all your interests do you: Make a move and tell them that you like them || Take time to ensure compatibility in other aspects",
  "Your partner's family disapproves of your relationship do you: Try to win their approval || Prioritise your partner's feelings over theirs",
  "Your ex wants to rekindle the relationship do you: Give them a chance || Respectfully decline",
  "Your partner's career is demanding, leaving little time for your relationship do you: Support their career || Express your need for more time together",
  "What do you prefer your partner to be: Younger/Older than you || Same age as you",
  "Your partner has a close relationship with an opposite-gender friend do you: Express your concerns || Trust your partner completely",
  "You're considering a relationship with a colleague do you: Hide your relationship from other work colleagues || Avoid workplace relationships altogether",
  "Your partner faces a life-altering decision that could impact your relationship do you: Encourage them to follow their dreams, even if it means separation || Try to influence their decision to benefit the relationship",
  "Your friend asks for advice but says it’s a secret do you give your advice and: Keep it between the both of you || Ask someone you trust for advice",
  "You catch your partner in a minor lie do you: Confront them || Act normally and observe them",
  "Your colleague asks for your opinion on a sensitive matter do you: Offer honest feedback || Hold back some details to avoid conflict",
  "A stranger asks for help but seems suspicious do you: Assist and provide help || Politely decline and walk away",
  "Your best friend shares a rumor about someone you know: Trust your best friend || Ask for clarification from that someone",
  "Your crush always expects you to initiate contact do you: Continue being the initiator || Wait for them to reach out",
  "You're offered two different career paths do you: Choose stability || Follow your passion",
  "You're faced with the decision to start a family or focus on your career do you: Prioritise family || Career advancement",
  "You're presented with the chance to live forever do you: Live an immortal life || Prefer a natural lifespan",
  "You're offered a glimpse into your future love life do you: Eagerly peek || Let love unfold naturally",
  "You have the choice between instant success now or gradual success in the future:  Immediate success || Gradual success",
  "At a party, there's a karaoke session would you: Participate and sing || Prefer to be an audience member",
  "You're asked to be the DJ at a friend's house party do you would you: Take on the role || feel the pressure and decline",
  "Your crush flirts but you are not sure do you: Flirt back || Ignore it to avoid confusion",
  "Sharing a bed with a friend on a trip do you:  Sleep comfortably together || Find it awkward and uncomfortable",
  "In a conflict, do you: Express your feelings even if it might hurt the other person || Hold back to avoid hurting them",
  "Attitude towards failure: Is failure a learning opportunity || A setback to be avoided",
  "Perspective on success: By achievements || By personal fulfilment",
  "Forgetting someone's name do you: Ask for it again || Try to navigate the conversation without using their name",
  "Accidentally waving at someone who wasn't actually greeting you do you: Laugh it off casually || Feel embarrassed about it",
  "Being caught staring at your crush do you: Smile and wave || Quickly look away, embarrassed",
  "Accidentally hitting like on a very old social media post of your crush do you: Unlike it immediately || Hope they don't notice",
  "Accidentally stepping on the bride's dress during the wedding do you: Apologise and help or ask for help to fix it || Try to ignore the mishap",
  "Which do you prefer being: Overdressed || Underdressed",
  "Encountering your favourite song on an empty dance floor do you: Dance freely without a care || Hesitate due to being alone",
  "Do you prefer your wedding venue to be: Indoors || Outdoors",
  "On your first dance together do you select a dance routine: That involves lifts or spins || Simple dance with no risk",
  "For the first dance do you: Choose a trendy romantic song || Choose a song that holds special meaning for both of you",
  "Deciding on a movie for a sleepover do you choose: A horror movie for thrills || A comedy movie for laughs",
  "If you had to be remembered for one thing, would you prefer to be known for: Your kindness || Your intelligence",
  "Would you rather: Dress casually comfortable for a first date || Choose a more formal and stylish outfit",
  "Would you prefer ending a first date with: A friendly hug or a handshake  ||  Leave it open for the other person to decide",
  "Do you prefer waiting for the other person to : Initiate post-date conversation || Reaching out first with a follow-up message",
  "Do you prefer: A short and sweet first date || A longer date that allows for more in-depth conversation and connection",
  "Do you prefer: A crowded and lively venue for a first date || A quiet and intimate setting",
  "Would you rather: Share a meal by trying each other's dishes || Stick to ordering separate items on a first date",
  "Do you prefer: Splitting the bill evenly || Alternating who pays on consecutive dates",
  "Do you prefer: Arriving at a first date location by walking together || Arriving separately and meeting there",
  "Would you rather Dress up for: An elegant classy dinner date || Casual dining experience on a first date",
  "Which do you prefer: Summer || Winter",
  "Ice cream preferences: Chocolate || Vanilla",
  "Which do you prefer, watching: Sunrise on the beach || Stargazing at night",
  "If you were a superhero would you rather have the ability to: Fly at a snail's pace || run as fast as a turtle",
  "If you had to pick, would you rather receive: A handwritten love letter || A surprise gift",
  "Would you rather have: A spontaneous adventure date || A planned romantic evening",
  "You call someone you are not close with by mistake and end the call right away but they call you back immediately do you: Quickly explain that it was by mistake || Continue the conversation without mentioning it",
  "Are you a: Coffee person || Tea person",
  "Which would you feel more safe touching : A lion || A snake",
  "Would you: Spend a whole day with your friends at haunted house || Spend a whole day in an empty room without",
];

for (let i = 1; i < questions.length; i++) {
  axios
    .post("http://localhost:3003/question", { question: questions[i] })
    .then((resp) => console.log(resp))
    .catch((error) => console.log(error));
}

app.listen(3004);
